apiVersion: v1
kind: Service
metadata:
  annotations:
    
  labels:
    app: api-gateway
  name: apigatewaysvc
spec:
  type: LoadBalancer
  ports:
  - name: "8080"
    port: 80
    targetPort: 8080
  selector:
    app: api-gateway

